"use client";

/* eslint-disable react/no-unescaped-entities */

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { ArrowLeft, ArrowRight, CircleHelp, Plus, Sparkles, Trash2 } from "lucide-react";
import { StageRail } from "./primitives";

type FormState = { question: string; application: string; population: string; horizon: string; constraints: string; claims: string[] };
type ApiSnapshot = { run?: { id?: string }; id?: string; revision?: string; snapshot?: { run?: { id?: string }; revision?: string } };
const blankInitial: FormState = { question: "", application: "", population: "", horizon: "", constraints: "", claims: [""] };
const aiReliabilityInitial: FormState = {
  question: "Does retrieval-augmented generation reduce factual hallucination in knowledge-grounded language generation compared with the same model without retrieval?",
  application: "Choose an evidence-grounding architecture for a domain-specific research question-answering assistant.",
  population: "Knowledge-grounded language generation and question-answering systems",
  horizon: "2020-present",
  constraints: "Prioritize empirical comparisons and record limitations caused by retrieval quality, task differences, and evaluator design.",
  claims: ["Retrieval augmentation reduces unsupported factual claims compared with an otherwise comparable non-retrieval model."],
};
function responseRun(data: ApiSnapshot): { id: string; revision: string } | null { const source = data.snapshot ?? data; const id = source.run?.id ?? data.run?.id ?? data.id; const revision = source.revision ?? data.revision; return id && revision ? { id, revision } : null; }

export function LiveIntake({ example = false }: { example?: boolean }) {
  const router = useRouter();
  const [form, setForm] = useState<FormState>(example ? aiReliabilityInitial : blankInitial); const [errors, setErrors] = useState<Record<string, string>>({}); const [state, setState] = useState<"idle" | "starting" | "decomposing" | "error">("idle"); const [error, setError] = useState("");
  const update = (key: keyof FormState, value: string | string[]) => setForm((current) => ({ ...current, [key]: value })); const updateClaim = (index: number, value: string) => update("claims", form.claims.map((claim, i) => i === index ? value : claim));
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); const claims = form.claims.map((claim) => claim.trim()).filter(Boolean); const nextErrors: Record<string, string> = {};
    if (!form.question.trim()) nextErrors.question = "Start with the question you want this investigation to answer."; if (!form.application.trim()) nextErrors.application = "Tell us where this answer will be used."; if (claims.length < 1) nextErrors.claims = "Add at least one claim to test."; if (claims.length > 3) nextErrors.claims = "Keep the first pass to three claims or fewer."; setErrors(nextErrors); if (Object.keys(nextErrors).length) return;
    setState("starting"); setError("");
    try {
      const intake = { originalQuestion: form.question.trim(), intendedApplication: form.application.trim(), populationOrGeography: form.population.trim() || "Not specified yet", timeHorizon: form.horizon.trim() || "Not specified yet", availableMaterialsOrBudget: "Not specified yet", desiredDepth: "Evidence packet with source-level provenance", constraints: [form.constraints.trim(), ...claims.map((claim) => `Seed claim: ${claim}`)].filter(Boolean), unansweredClarifications: [] };
      const created = await fetch("/api/runs", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedRevision: null, intake }) }); const data = await created.json().catch(() => ({})) as ApiSnapshot & { error?: { message?: string }; message?: string }; if (!created.ok) throw new Error(data.error?.message ?? data.message ?? "We couldn't create the investigation."); const run = responseRun(data); if (!run) throw new Error("The investigation was created, but its run link was missing. Please try again.");
      setState("decomposing"); const continued = await fetch(`/api/runs/${encodeURIComponent(run.id)}/continue`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ expectedRevision: run.revision }) }); if (!continued.ok) { const continuationError = await continued.json().catch(() => ({})) as { error?: { message?: string }; message?: string }; throw new Error(continuationError.error?.message ?? continuationError.message ?? "The claim analysis could not start."); } router.push(`/runs/${encodeURIComponent(run.id)}`);
    } catch (cause) { setState("error"); setError(cause instanceof Error ? cause.message : "Something went wrong. Please try again."); }
  }
  const busy = state === "starting" || state === "decomposing";
  return <main className="research-intake"><header className="research-intake-header"><Link href="/" className="research-back"><ArrowLeft size={15} /> EvidenceForge</Link><span>New investigation</span></header><div className="research-intake-wrap"><StageRail stages={["Question", "Evidence packet", "Analysis", "Decision"]} active={0} /><div className="research-intake-heading"><p className="research-kicker"><Sparkles size={14} /> Start with what you don't know</p><h1>What are you trying to find out?</h1><p>Give us the question behind the question. EvidenceForge will help turn it into claims you can actually test.</p></div><form className="research-intake-form" onSubmit={submit} noValidate>
    <div className="research-field research-field-wide"><label htmlFor="question">Research question <span>Required</span></label><textarea id="question" rows={3} value={form.question} onChange={(e) => update("question", e.target.value)} placeholder="e.g. Does retrieval improve factual accuracy in language models?" aria-invalid={Boolean(errors.question)} aria-describedby={errors.question ? "question-error" : "question-help"} />{errors.question ? <small id="question-error" className="research-field-error">{errors.question}</small> : <small id="question-help">Write it as an open question, not a conclusion.</small>}</div>
    <div className="research-field"><label htmlFor="application">Intended application <span>Required</span></label><textarea id="application" rows={3} value={form.application} onChange={(e) => update("application", e.target.value)} placeholder="What decision, product, or practice will this inform?" aria-invalid={Boolean(errors.application)} />{errors.application && <small className="research-field-error">{errors.application}</small>}</div><div className="research-field"><label htmlFor="population">Population or context <span>Optional</span></label><input id="population" value={form.population} onChange={(e) => update("population", e.target.value)} placeholder="Who or where does this apply to?" /></div><div className="research-field"><label htmlFor="horizon">Time horizon <span>Optional</span></label><input id="horizon" value={form.horizon} onChange={(e) => update("horizon", e.target.value)} placeholder="e.g. 2020–present" /></div><div className="research-field research-field-wide"><label htmlFor="constraints">Constraints and boundaries <span>Optional</span></label><textarea id="constraints" rows={2} value={form.constraints} onChange={(e) => update("constraints", e.target.value)} placeholder="What should the investigation include or avoid?" /></div>
    <fieldset className="research-claims research-field-wide"><legend>Claims to test <span>1–3 required</span></legend><p className="research-claims-help">Add your starting hypotheses. We’ll decompose and challenge them after you begin.</p>{form.claims.map((claim, index) => <div className="research-claim-row" key={index}><label htmlFor={`claim-${index}`} className="sr-only">Claim {index + 1}</label><input id={`claim-${index}`} value={claim} onChange={(e) => updateClaim(index, e.target.value)} placeholder={`Claim ${index + 1} — a statement you think may be true`} />{form.claims.length > 1 && <button type="button" aria-label={`Remove claim ${index + 1}`} className="research-icon-button" onClick={() => update("claims", form.claims.filter((_, i) => i !== index))}><Trash2 size={15} /></button>}</div>)}{form.claims.length < 3 && <button type="button" className="research-add-claim" onClick={() => update("claims", [...form.claims, ""])}><Plus size={15} /> Add another claim</button>}{errors.claims && <small className="research-field-error">{errors.claims}</small>}</fieldset>
    {state === "error" && <div className="research-intake-error" role="alert"><CircleHelp size={18} /><div><strong>We couldn't start this investigation.</strong><p>{error}</p><button type="button" onClick={() => setState("idle")}>Review and try again</button></div></div>}<div className="research-intake-submit"><p><CircleHelp size={14} /> You can edit the generated claims before any sources are collected.</p><button className="research-button research-button-primary" disabled={busy}>{state === "starting" ? "Creating investigation…" : state === "decomposing" ? "Shaping your claims…" : <>Begin investigation <ArrowRight size={17} /></>}</button></div>
  </form></div></main>;
}
